on:
  workflow_call:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: actions/setup-node@v2
