on:
  workflow_call:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v3
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - uses: actions/setup-node@v4
