on:
  workflow_call:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v5
      - uses: actions/setup-python@v6
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
      - uses: actions/setup-node@v5
